[2023-11-14T00:07:35.963+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_25/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_25 permission to 509
[2023-11-14T00:07:35.967+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_25/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_25 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_25/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_25'
[2023-11-14T00:07:37.872+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_25/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_25 permission to 509
[2023-11-14T00:07:37.874+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_25/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_25 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_25/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_25'
[2023-11-14T00:07:37.998+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_dag_25.setup_and_run_simulator_task_25 scheduled__2023-11-13T00:00:00+00:00 [queued]>
[2023-11-14T00:07:38.025+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_dag_25.setup_and_run_simulator_task_25 scheduled__2023-11-13T00:00:00+00:00 [queued]>
[2023-11-14T00:07:38.027+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-11-14T00:07:38.132+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): setup_and_run_simulator_task_25> on 2023-11-13 00:00:00+00:00
[2023-11-14T00:07:38.202+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simulator_dag_25', 'setup_and_run_simulator_task_25', 'scheduled__2023-11-13T00:00:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/timeseries.py', '--cfg-path', '/tmp/tmp6wlnkaf9']
[2023-11-14T00:07:38.224+0000] {standard_task_runner.py:85} INFO - Job 149: Subtask setup_and_run_simulator_task_25
[2023-11-14T00:07:38.206+0000] {standard_task_runner.py:57} INFO - Started process 12795 to run task
[2023-11-14T00:07:38.459+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_25/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_25 permission to 509
[2023-11-14T00:07:38.466+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_25/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_25 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_25/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_25'
[2023-11-14T00:07:38.561+0000] {task_command.py:416} INFO - Running <TaskInstance: simulator_dag_25.setup_and_run_simulator_task_25 scheduled__2023-11-13T00:00:00+00:00 [running]> on host 84c765240aba
[2023-11-14T00:07:39.006+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_dag_25' AIRFLOW_CTX_TASK_ID='setup_and_run_simulator_task_25' AIRFLOW_CTX_EXECUTION_DATE='2023-11-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-13T00:00:00+00:00'
[2023-11-14T00:08:09.861+0000] {logging_mixin.py:154} INFO - Standard Output: File 'TimeSeries_daily_exist_weekly_exist_noise_small_trend_exist_cycle_exist_outliers_5%_freq_1H_missing_6%.csv' generated.
[2023-11-14T00:08:09.862+0000] {logging_mixin.py:154} INFO - Standard Error: Traceback (most recent call last):
  File "/djangoapp/Task1/main.py", line 74, in <module>
    main()
  File "/djangoapp/Task1/main.py", line 69, in main
    director.generate_multiple_datasets(config_attributes,data_saving)
  File "/djangoapp/Task1/TimeSeriesDirector.py", line 130, in generate_multiple_datasets
    data_saver.save_file(time_series_data, i, config)
  File "/djangoapp/Task1/FolderSaver.py", line 41, in save_file
    df = df.to_csv(config_file_path + str(counter + 1) + '.csv', encoding='utf-8', index=False)
  File "/home/***/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/***/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/***/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/***/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/***/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/djangoapp/Task1/Task1/sample_datasets'
[2023-11-14T00:08:09.863+0000] {logging_mixin.py:154} INFO - this is my stattututututs 1
[2023-11-14T00:08:09.876+0000] {logging_mixin.py:154} INFO - this is hiiiim <Thread(Thread-1, initial)>
[2023-11-14T00:08:09.884+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-14T00:08:09.919+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=simulator_dag_25, task_id=setup_and_run_simulator_task_25, execution_date=20231113T000000, start_date=20231114T000738, end_date=20231114T000809
[2023-11-14T00:08:10.098+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-14T00:08:10.173+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
