[2023-11-16T08:42:41.114+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509
[2023-11-16T08:42:41.117+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17'
[2023-11-16T08:42:41.865+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509
[2023-11-16T08:42:41.878+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17'
[2023-11-16T08:42:42.087+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_dag_17.setup_and_run_simulator_task_17 scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-16T08:42:42.141+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_dag_17.setup_and_run_simulator_task_17 scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-16T08:42:42.142+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-11-16T08:42:43.971+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): setup_and_run_simulator_task_17> on 2023-11-15 00:00:00+00:00
[2023-11-16T08:42:44.059+0000] {standard_task_runner.py:57} INFO - Started process 25404 to run task
[2023-11-16T08:42:44.092+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simulator_dag_17', 'setup_and_run_simulator_task_17', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/timeseries.py', '--cfg-path', '/tmp/tmp4wr_prdb']
[2023-11-16T08:42:44.137+0000] {standard_task_runner.py:85} INFO - Job 271: Subtask setup_and_run_simulator_task_17
[2023-11-16T08:42:44.695+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509
[2023-11-16T08:42:44.699+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17'
[2023-11-16T08:42:44.736+0000] {task_command.py:416} INFO - Running <TaskInstance: simulator_dag_17.setup_and_run_simulator_task_17 scheduled__2023-11-15T00:00:00+00:00 [running]> on host 84c765240aba
[2023-11-16T08:42:45.677+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_dag_17' AIRFLOW_CTX_TASK_ID='setup_and_run_simulator_task_17' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-16T14:43:59.963+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509
[2023-11-16T14:43:59.968+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17'
[2023-11-16T14:44:00.058+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509
[2023-11-16T14:44:00.061+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-15T00:00:00+00:00/task_id=setup_and_run_simulator_task_17'
[2023-11-16T14:44:00.134+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: simulator_dag_17.setup_and_run_simulator_task_17 scheduled__2023-11-15T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-11-16T14:44:00.158+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: simulator_dag_17.setup_and_run_simulator_task_17 scheduled__2023-11-15T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-11-16T14:44:00.164+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-11-17T10:50:43.416+0000] {local_task_job_runner.py:205} ERROR - Heartbeat time limit exceeded!
[2023-11-17T10:50:44.626+0000] {process_utils.py:131} INFO - Sending 15 to group 25404. PIDs of all processes in the group: [25412, 25404]
[2023-11-17T10:50:44.788+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 25404
[2023-11-17T10:50:45.093+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-11-17T10:50:46.940+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/timeseries.py", line 54, in setup_and_run_simulator
    trigger_run_simulator(simulator_data_dict, **kwargs)
  File "/opt/airflow/dags/timeseries.py", line 59, in trigger_run_simulator
    trigger_simulator({"id": simulator_data_dict["id"]})
  File "/djangoapp/simulator_api/views.py", line 314, in trigger_simulator
    simulator_thread = threading.Thread(target=run_simulator_thread(dataset))
  File "/djangoapp/simulator_api/views.py", line 299, in run_simulator_thread
    stdout, stderr = process.communicate(input=data)
  File "/usr/local/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1884, in _communicate
    ready = selector.select(timeout)
  File "/usr/local/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-11-17T10:50:48.206+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=simulator_dag_17, task_id=setup_and_run_simulator_task_17, execution_date=20231115T000000, start_date=20231116T084242, end_date=20231117T105048
[2023-11-17T10:50:49.225+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 271 for task setup_and_run_simulator_task_17 (Task received SIGTERM signal; 25404)
[2023-11-17T10:50:49.849+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=25412, status='terminated', started='2023-11-16 08:42:45') (25412) terminated with exit code None
[2023-11-17T10:50:49.883+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=25404, status='terminated', exitcode=1, started='2023-11-16 08:42:43') (25404) terminated with exit code 1
