[2023-11-12T19:45:05.979+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_4/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_4 permission to 509
[2023-11-12T19:45:05.981+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_4/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_4 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_4/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_4'
[2023-11-12T19:45:06.043+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_4/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_4 permission to 509
[2023-11-12T19:45:06.046+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_4/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_4 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_4/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_4'
[2023-11-12T19:45:06.125+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_dag_4.setup_and_run_simulator_task_4 scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-12T19:45:06.147+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_dag_4.setup_and_run_simulator_task_4 scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-12T19:45:06.149+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-11-12T19:45:06.187+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): setup_and_run_simulator_task_4> on 2023-11-11 00:00:00+00:00
[2023-11-12T19:45:06.200+0000] {standard_task_runner.py:57} INFO - Started process 1950 to run task
[2023-11-12T19:45:06.212+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simulator_dag_4', 'setup_and_run_simulator_task_4', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/timeseries.py', '--cfg-path', '/tmp/tmpg7xx6283']
[2023-11-12T19:45:06.220+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask setup_and_run_simulator_task_4
[2023-11-12T19:45:06.334+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_4/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_4 permission to 509
[2023-11-12T19:45:06.336+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_4/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_4 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_4/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_4'
[2023-11-12T19:45:06.350+0000] {task_command.py:416} INFO - Running <TaskInstance: simulator_dag_4.setup_and_run_simulator_task_4 scheduled__2023-11-11T00:00:00+00:00 [running]> on host e15777c5c324
[2023-11-12T19:45:06.606+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_dag_4' AIRFLOW_CTX_TASK_ID='setup_and_run_simulator_task_4' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-12T19:45:06.618+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/timeseries.py", line 55, in setup_and_run_simulator
    Path(working_directory).resolve().chdir()
AttributeError: 'PosixPath' object has no attribute 'chdir'
[2023-11-12T19:45:06.649+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=simulator_dag_4, task_id=setup_and_run_simulator_task_4, execution_date=20231111T000000, start_date=20231112T194506, end_date=20231112T194506
[2023-11-12T19:45:06.680+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task setup_and_run_simulator_task_4 ('PosixPath' object has no attribute 'chdir'; 1950)
[2023-11-12T19:45:06.724+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-12T19:45:06.760+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
