[2023-11-14T00:09:23.845+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_52/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_52 permission to 509
[2023-11-14T00:09:23.858+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_52/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_52 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_52/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_52'
[2023-11-14T00:09:23.966+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_52/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_52 permission to 509
[2023-11-14T00:09:23.972+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_52/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_52 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_52/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_52'
[2023-11-14T00:09:24.148+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_dag_52.setup_and_run_simulator_task_52 scheduled__2023-11-13T00:00:00+00:00 [queued]>
[2023-11-14T00:09:24.205+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_dag_52.setup_and_run_simulator_task_52 scheduled__2023-11-13T00:00:00+00:00 [queued]>
[2023-11-14T00:09:24.239+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-11-14T00:09:24.306+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): setup_and_run_simulator_task_52> on 2023-11-13 00:00:00+00:00
[2023-11-14T00:09:24.326+0000] {standard_task_runner.py:57} INFO - Started process 13691 to run task
[2023-11-14T00:09:24.347+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simulator_dag_52', 'setup_and_run_simulator_task_52', 'scheduled__2023-11-13T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/timeseries.py', '--cfg-path', '/tmp/tmprv4z314u']
[2023-11-14T00:09:24.363+0000] {standard_task_runner.py:85} INFO - Job 192: Subtask setup_and_run_simulator_task_52
[2023-11-14T00:09:24.531+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_52/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_52 permission to 509
[2023-11-14T00:09:24.534+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_52/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_52 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_52/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_52'
[2023-11-14T00:09:24.549+0000] {task_command.py:416} INFO - Running <TaskInstance: simulator_dag_52.setup_and_run_simulator_task_52 scheduled__2023-11-13T00:00:00+00:00 [running]> on host 84c765240aba
[2023-11-14T00:09:24.815+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_dag_52' AIRFLOW_CTX_TASK_ID='setup_and_run_simulator_task_52' AIRFLOW_CTX_EXECUTION_DATE='2023-11-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-13T00:00:00+00:00'
[2023-11-14T00:09:27.035+0000] {logging_mixin.py:154} INFO - Standard Output: 
[2023-11-14T00:09:27.037+0000] {logging_mixin.py:154} INFO - Standard Error: Traceback (most recent call last):
  File "/djangoapp/Task1/main.py", line 1, in <module>
    from datetime import datetime, timedelta
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1510, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1553, in _fill_cache
OSError: [Errno 12] Cannot allocate memory: '/djangoapp/Task1'
[2023-11-14T00:09:27.039+0000] {logging_mixin.py:154} INFO - this is my stattututututs 1
[2023-11-14T00:09:27.155+0000] {logging_mixin.py:154} INFO - this is hiiiim <Thread(Thread-1, initial)>
[2023-11-14T00:09:27.163+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-14T00:09:27.226+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=simulator_dag_52, task_id=setup_and_run_simulator_task_52, execution_date=20231113T000000, start_date=20231114T000924, end_date=20231114T000927
[2023-11-14T00:09:27.423+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-14T00:09:27.473+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
