[2023-11-14T00:08:32.324+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_22/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_22 permission to 509
[2023-11-14T00:08:32.326+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_22/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_22 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_22/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_22'
[2023-11-14T00:08:32.566+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_22/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_22 permission to 509
[2023-11-14T00:08:32.579+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_22/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_22 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_22/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_22'
[2023-11-14T00:08:32.745+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_dag_22.setup_and_run_simulator_task_22 scheduled__2023-11-13T00:00:00+00:00 [queued]>
[2023-11-14T00:08:32.785+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_dag_22.setup_and_run_simulator_task_22 scheduled__2023-11-13T00:00:00+00:00 [queued]>
[2023-11-14T00:08:32.789+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-11-14T00:08:32.875+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): setup_and_run_simulator_task_22> on 2023-11-13 00:00:00+00:00
[2023-11-14T00:08:32.890+0000] {standard_task_runner.py:57} INFO - Started process 13156 to run task
[2023-11-14T00:08:32.917+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simulator_dag_22', 'setup_and_run_simulator_task_22', 'scheduled__2023-11-13T00:00:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/timeseries.py', '--cfg-path', '/tmp/tmp9u3q8kjy']
[2023-11-14T00:08:32.937+0000] {standard_task_runner.py:85} INFO - Job 169: Subtask setup_and_run_simulator_task_22
[2023-11-14T00:08:33.198+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_22/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_22 permission to 509
[2023-11-14T00:08:33.200+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_22/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_22 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_22/run_id=scheduled__2023-11-13T00:00:00+00:00/task_id=setup_and_run_simulator_task_22'
[2023-11-14T00:08:33.213+0000] {task_command.py:416} INFO - Running <TaskInstance: simulator_dag_22.setup_and_run_simulator_task_22 scheduled__2023-11-13T00:00:00+00:00 [running]> on host 84c765240aba
[2023-11-14T00:08:33.537+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_dag_22' AIRFLOW_CTX_TASK_ID='setup_and_run_simulator_task_22' AIRFLOW_CTX_EXECUTION_DATE='2023-11-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-13T00:00:00+00:00'
[2023-11-14T00:08:47.271+0000] {logging_mixin.py:154} INFO - Standard Output: File 'TimeSeries_daily_exist_weekly_exist_noise_small_trend_exist_cycle_exist_outliers_5%_freq_1H_missing_6%.csv' generated.
[2023-11-14T00:08:47.272+0000] {logging_mixin.py:154} INFO - Standard Error: Traceback (most recent call last):
  File "/djangoapp/Task1/main.py", line 74, in <module>
    main()
  File "/djangoapp/Task1/main.py", line 69, in main
    director.generate_multiple_datasets(config_attributes,data_saving)
  File "/djangoapp/Task1/TimeSeriesDirector.py", line 130, in generate_multiple_datasets
    data_saver.save_file(time_series_data, i, config)
  File "/djangoapp/Task1/FolderSaver.py", line 41, in save_file
    df = df.to_csv(config_file_path + str(counter + 1) + '.csv', encoding='utf-8', index=False)
  File "/home/***/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/***/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/***/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/***/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/***/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/djangoapp/Task1/Task1/sample_datasets'
[2023-11-14T00:08:47.273+0000] {logging_mixin.py:154} INFO - this is my stattututututs 1
[2023-11-14T00:08:47.346+0000] {logging_mixin.py:154} INFO - this is hiiiim <Thread(Thread-1, initial)>
[2023-11-14T00:08:47.353+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-14T00:08:47.396+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=simulator_dag_22, task_id=setup_and_run_simulator_task_22, execution_date=20231113T000000, start_date=20231114T000832, end_date=20231114T000847
[2023-11-14T00:08:47.488+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-14T00:08:47.522+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
