[2023-11-13T20:05:14.307+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509
[2023-11-13T20:05:14.308+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=setup_and_run_simulator_task_17'
[2023-11-13T20:05:14.341+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509
[2023-11-13T20:05:14.342+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=setup_and_run_simulator_task_17'
[2023-11-13T20:05:14.368+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_dag_17.setup_and_run_simulator_task_17 scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-13T20:05:14.378+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_dag_17.setup_and_run_simulator_task_17 scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-13T20:05:14.379+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2023-11-13T20:05:14.395+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): setup_and_run_simulator_task_17> on 2023-11-12 00:00:00+00:00
[2023-11-13T20:05:14.402+0000] {standard_task_runner.py:57} INFO - Started process 9675 to run task
[2023-11-13T20:05:14.406+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simulator_dag_17', 'setup_and_run_simulator_task_17', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/timeseries.py', '--cfg-path', '/tmp/tmpeuh2z9cp']
[2023-11-13T20:05:14.409+0000] {standard_task_runner.py:85} INFO - Job 147: Subtask setup_and_run_simulator_task_17
[2023-11-13T20:05:14.456+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509
[2023-11-13T20:05:14.457+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=setup_and_run_simulator_task_17'
[2023-11-13T20:05:14.461+0000] {task_command.py:416} INFO - Running <TaskInstance: simulator_dag_17.setup_and_run_simulator_task_17 scheduled__2023-11-12T00:00:00+00:00 [running]> on host 84c765240aba
[2023-11-13T20:05:14.545+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_dag_17' AIRFLOW_CTX_TASK_ID='setup_and_run_simulator_task_17' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-14T00:08:14.672+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2023-11-14T00:08:14.678+0000] {process_utils.py:131} INFO - Sending 15 to group 9675. PIDs of all processes in the group: [9676, 9675]
[2023-11-14T00:08:14.690+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 9675
[2023-11-14T00:08:14.694+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-11-14T00:08:14.716+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/timeseries.py", line 54, in setup_and_run_simulator
    trigger_run_simulator(simulator_data_dict, **kwargs)
  File "/opt/airflow/dags/timeseries.py", line 59, in trigger_run_simulator
    trigger_simulator({"id": simulator_data_dict["id"]})
  File "/djangoapp/simulator_api/views.py", line 314, in trigger_simulator
    simulator_thread = threading.Thread(target=run_simulator_thread(dataset))
  File "/djangoapp/simulator_api/views.py", line 299, in run_simulator_thread
    stdout, stderr = process.communicate(input=data)
  File "/usr/local/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1884, in _communicate
    ready = selector.select(timeout)
  File "/usr/local/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-11-14T00:08:14.754+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=simulator_dag_17, task_id=setup_and_run_simulator_task_17, execution_date=20231112T000000, start_date=20231113T200514, end_date=20231114T000814
[2023-11-14T00:08:14.827+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 147 for task setup_and_run_simulator_task_17 (Task received SIGTERM signal; 9675)
[2023-11-14T00:08:14.857+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9675, status='terminated', exitcode=1, started='20:05:14') (9675) terminated with exit code 1
[2023-11-14T00:08:14.859+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9676, status='terminated', started='20:05:14') (9676) terminated with exit code None
