[2023-11-17T10:52:30.395+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_15/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_15 permission to 509
[2023-11-17T10:52:30.407+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_15/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_15 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_15/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_15'
[2023-11-17T10:52:30.562+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_15/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_15 permission to 509
[2023-11-17T10:52:30.565+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_15/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_15 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_15/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_15'
[2023-11-17T10:52:30.729+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_dag_15.setup_and_run_simulator_task_15 scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-17T10:52:30.807+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_dag_15.setup_and_run_simulator_task_15 scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-17T10:52:30.818+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-11-17T10:52:30.917+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): setup_and_run_simulator_task_15> on 2023-11-16 00:00:00+00:00
[2023-11-17T10:52:30.959+0000] {standard_task_runner.py:57} INFO - Started process 37551 to run task
[2023-11-17T10:52:30.995+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simulator_dag_15', 'setup_and_run_simulator_task_15', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '349', '--raw', '--subdir', 'DAGS_FOLDER/timeseries.py', '--cfg-path', '/tmp/tmp6z5lrpv5']
[2023-11-17T10:52:31.036+0000] {standard_task_runner.py:85} INFO - Job 349: Subtask setup_and_run_simulator_task_15
[2023-11-17T10:52:31.299+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_15/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_15 permission to 509
[2023-11-17T10:52:31.301+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_15/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_15 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_15/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_15'
[2023-11-17T10:52:31.310+0000] {task_command.py:416} INFO - Running <TaskInstance: simulator_dag_15.setup_and_run_simulator_task_15 scheduled__2023-11-16T00:00:00+00:00 [running]> on host 84c765240aba
[2023-11-17T10:52:31.799+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_dag_15' AIRFLOW_CTX_TASK_ID='setup_and_run_simulator_task_15' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-17T10:52:32.613+0000] {logging_mixin.py:154} INFO - Standard Output: 
[2023-11-17T10:52:32.616+0000] {logging_mixin.py:154} INFO - Standard Error: Traceback (most recent call last):
  File "/djangoapp/Task1/main.py", line 1, in <module>
    from datetime import datetime, timedelta
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1510, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1553, in _fill_cache
OSError: [Errno 12] Cannot allocate memory: '/djangoapp/Task1'
[2023-11-17T10:52:32.617+0000] {logging_mixin.py:154} INFO - this is my stattututututs 1
[2023-11-17T10:52:32.627+0000] {logging_mixin.py:154} INFO - this is hiiiim <Thread(Thread-1, initial)>
[2023-11-17T10:52:32.646+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-17T10:52:32.693+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=simulator_dag_15, task_id=setup_and_run_simulator_task_15, execution_date=20231116T000000, start_date=20231117T105230, end_date=20231117T105232
[2023-11-17T10:52:32.792+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-17T10:52:32.851+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
