[2023-11-12T19:57:03.511+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509
[2023-11-12T19:57:03.513+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8'
[2023-11-12T19:57:03.547+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509
[2023-11-12T19:57:03.549+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8'
[2023-11-12T19:57:03.582+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_dag_8.setup_and_run_simulator_task_8 scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-12T19:57:03.592+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_dag_8.setup_and_run_simulator_task_8 scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-12T19:57:03.593+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2023-11-12T19:57:03.607+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): setup_and_run_simulator_task_8> on 2023-11-11 00:00:00+00:00
[2023-11-12T19:57:03.614+0000] {standard_task_runner.py:57} INFO - Started process 2139 to run task
[2023-11-12T19:57:03.618+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simulator_dag_8', 'setup_and_run_simulator_task_8', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/timeseries.py', '--cfg-path', '/tmp/tmp_85a4jcv']
[2023-11-12T19:57:03.621+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask setup_and_run_simulator_task_8
[2023-11-12T19:57:03.675+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509
[2023-11-12T19:57:03.676+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8'
[2023-11-12T19:57:03.682+0000] {task_command.py:416} INFO - Running <TaskInstance: simulator_dag_8.setup_and_run_simulator_task_8 scheduled__2023-11-11T00:00:00+00:00 [running]> on host e15777c5c324
[2023-11-12T19:57:03.768+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_dag_8' AIRFLOW_CTX_TASK_ID='setup_and_run_simulator_task_8' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-12T19:57:03.771+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/timeseries.py", line 55, in setup_and_run_simulator
    os.chmod(working_directory,0o755)
PermissionError: [Errno 1] Operation not permitted: '/djangoapp/Task1'
[2023-11-12T19:57:03.787+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=simulator_dag_8, task_id=setup_and_run_simulator_task_8, execution_date=20231111T000000, start_date=20231112T195703, end_date=20231112T195703
[2023-11-12T19:57:03.802+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task setup_and_run_simulator_task_8 ([Errno 1] Operation not permitted: '/djangoapp/Task1'; 2139)
[2023-11-12T19:57:03.849+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-12T19:57:03.865+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
