[2023-11-12T19:57:15.869+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509
[2023-11-12T19:57:15.871+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8'
[2023-11-12T19:57:15.913+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509
[2023-11-12T19:57:15.914+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8'
[2023-11-12T19:57:15.955+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_dag_8.setup_and_run_simulator_task_8 scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-12T19:57:15.969+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_dag_8.setup_and_run_simulator_task_8 scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-12T19:57:15.970+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-11-12T19:57:15.993+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): setup_and_run_simulator_task_8> on 2023-11-11 00:00:00+00:00
[2023-11-12T19:57:16.003+0000] {standard_task_runner.py:57} INFO - Started process 2142 to run task
[2023-11-12T19:57:16.010+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simulator_dag_8', 'setup_and_run_simulator_task_8', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/timeseries.py', '--cfg-path', '/tmp/tmpnidjftr_']
[2023-11-12T19:57:16.015+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask setup_and_run_simulator_task_8
[2023-11-12T19:57:16.100+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509
[2023-11-12T19:57:16.101+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_8/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_8'
[2023-11-12T19:57:16.107+0000] {task_command.py:416} INFO - Running <TaskInstance: simulator_dag_8.setup_and_run_simulator_task_8 scheduled__2023-11-11T00:00:00+00:00 [running]> on host e15777c5c324
[2023-11-12T19:57:16.216+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_dag_8' AIRFLOW_CTX_TASK_ID='setup_and_run_simulator_task_8' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-12T19:57:16.220+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/timeseries.py", line 55, in setup_and_run_simulator
    os.chmod(working_directory,0o755)
PermissionError: [Errno 1] Operation not permitted: '/djangoapp/Task1'
[2023-11-12T19:57:16.239+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=simulator_dag_8, task_id=setup_and_run_simulator_task_8, execution_date=20231111T000000, start_date=20231112T195715, end_date=20231112T195716
[2023-11-12T19:57:16.257+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task setup_and_run_simulator_task_8 ([Errno 1] Operation not permitted: '/djangoapp/Task1'; 2142)
[2023-11-12T19:57:16.283+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-12T19:57:16.313+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
