[2023-11-17T10:52:19.209+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_30/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_30 permission to 509
[2023-11-17T10:52:19.212+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_30/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_30 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_30/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_30'
[2023-11-17T10:52:19.338+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_30/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_30 permission to 509
[2023-11-17T10:52:19.355+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_30/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_30 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_30/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_30'
[2023-11-17T10:52:19.499+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_dag_30.setup_and_run_simulator_task_30 scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-17T10:52:19.568+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_dag_30.setup_and_run_simulator_task_30 scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-17T10:52:19.570+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-11-17T10:52:19.667+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): setup_and_run_simulator_task_30> on 2023-11-16 00:00:00+00:00
[2023-11-17T10:52:19.715+0000] {standard_task_runner.py:57} INFO - Started process 37416 to run task
[2023-11-17T10:52:19.756+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simulator_dag_30', 'setup_and_run_simulator_task_30', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '343', '--raw', '--subdir', 'DAGS_FOLDER/timeseries.py', '--cfg-path', '/tmp/tmpjnjk1g2d']
[2023-11-17T10:52:19.781+0000] {standard_task_runner.py:85} INFO - Job 343: Subtask setup_and_run_simulator_task_30
[2023-11-17T10:52:20.107+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_30/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_30 permission to 509
[2023-11-17T10:52:20.109+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_30/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_30 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_30/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=setup_and_run_simulator_task_30'
[2023-11-17T10:52:20.117+0000] {task_command.py:416} INFO - Running <TaskInstance: simulator_dag_30.setup_and_run_simulator_task_30 scheduled__2023-11-16T00:00:00+00:00 [running]> on host 84c765240aba
[2023-11-17T10:52:20.551+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_dag_30' AIRFLOW_CTX_TASK_ID='setup_and_run_simulator_task_30' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-17T10:52:23.757+0000] {logging_mixin.py:154} INFO - Standard Output: 
[2023-11-17T10:52:23.759+0000] {logging_mixin.py:154} INFO - Standard Error: Traceback (most recent call last):
  File "/djangoapp/Task1/main.py", line 2, in <module>
    import pandas as pd
  File "/home/***/.local/lib/python3.8/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(_dependency)
  File "/home/***/.local/lib/python3.8/site-packages/numpy/__init__.py", line 152, in <module>
    from . import random
  File "/home/***/.local/lib/python3.8/site-packages/numpy/random/__init__.py", line 180, in <module>
    from . import _pickle
  File "/home/***/.local/lib/python3.8/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
  File "bit_generator.pyx", line 38, in init numpy.random.bit_generator
  File "/usr/local/lib/python3.8/secrets.py", line 15, in <module>
    import base64
  File "/usr/local/lib/python3.8/base64.py", line 11, in <module>
    import binascii
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1510, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1553, in _fill_cache
OSError: [Errno 12] Cannot allocate memory: '/djangoapp/Task1'
[2023-11-17T10:52:23.762+0000] {logging_mixin.py:154} INFO - this is my stattututututs 1
[2023-11-17T10:52:23.771+0000] {logging_mixin.py:154} INFO - this is hiiiim <Thread(Thread-1, initial)>
[2023-11-17T10:52:23.774+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-17T10:52:23.879+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=simulator_dag_30, task_id=setup_and_run_simulator_task_30, execution_date=20231116T000000, start_date=20231117T105219, end_date=20231117T105223
[2023-11-17T10:52:24.485+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-17T10:52:24.554+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
